dist: trusty
language: cpp

#addons:
#  apt:
#    sources:
#      - ubuntu-toolchain-r-test
#    packages:
#      - wget
#      - pkg-config

before_install:
  - sudo apt-get install -y openjdk-8-jdk

install:
  - echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
  - curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add - 
  - sudo apt-get update && sudo apt-get install bazel
  - sudo apt-get upgrade bazel

script:
  - bazel build ...
  - bazel test ...
