dist: trusty
language: cpp
sudo: required

addons:
  apd:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - pkg-config

before_install:
  - wget https://github.com/bazelbuild/bazel/releases/download/0.17.2/bazel-0.17.2-installer-linux-x86_64.sh 
  - chmod +x bazel-0.17.2-installer-linux-x86_64.sh
  - ./bazel-0.17.2-installer-linux-x86_64.sh --user
  - export PATH="$PATH:$HOME/bin"  
  - sed -i 's/c++14/c++1y/g' tools/bazel.rc

script:
  - bazel build ...
  - bazel test ...
